server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Healthcheck do container
    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "Healthy\n";
    }

    location ~ ^/(.+)/$ {
        return 301 $scheme://$host/$1;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~ \.html$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    error_page 404 =404 /404.html;
}
