import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [vue()],
  // @ts-expect-error vite-ssg consumes this Vite config extension.
  ssgOptions: {
    includedRoutes: () => [
      '/',
      '/produto',
      '/features',
      '/platform',
      '/pricing',
      '/compare',
      '/tools',
      '/about',
      '/contact',
      '/privacy',
      '/cookies',
      '/terms',
      '/compare/brewfather',
      '/compare/beersmith',
      '/compare/brewers-friend',
      '/en',
      '/en/produto',
      '/en/features',
      '/en/platform',
      '/en/pricing',
      '/en/compare',
      '/en/tools',
      '/en/about',
      '/en/contact',
      '/en/privacy',
      '/en/cookies',
      '/en/terms',
      '/en/compare/brewfather',
      '/en/compare/beersmith',
      '/en/compare/brewers-friend',
      '/es',
      '/es/produto',
      '/es/features',
      '/es/platform',
      '/es/pricing',
      '/es/compare',
      '/es/tools',
      '/es/about',
      '/es/contact',
      '/es/privacy',
      '/es/cookies',
      '/es/terms',
      '/es/compare/brewfather',
      '/es/compare/beersmith',
      '/es/compare/brewers-friend',
    ],
  },
})
