import type { Locale, PageKind, PageMeta, ScreenshotProps } from './types'

export type MarketingPageKind = Exclude<PageKind, 'privacy' | 'cookies' | 'terms'>

export interface UiCopy {
  nav: {
    product: string
    platform: string
    tools: string
    compare: string
    pricing: string
    resources: string
    login: string
    start: string
    explore: string
    menu: string
    close: string
  }
  footer: { ctaTitle: string; ctaBody: string; ctaAction: string; explore: string; product: string; documentation: string; modules: string; exploreProcess: string; exploreModules: string; explorePricing: string; exploreAbout: string; brewPilot: string; supportLegal: string; eyebrow: string; signature: string; resources: string; recipes: string; batches: string; inventory: string; profiles: string; howItWorks: string; about: string; support: string; privacy: string; cookies: string; terms: string; termsOfUse: string }
  common: { soon: string; viewMore: string; appOnly: string; pending: string; backHome: string; email: string; language: string; privacyConsent: string; productStories: string; faq: string }
  consent: { title: string; body: string; accept: string; reject: string; settings: string }
  cycle: string[]
  cycleDescriptions: string[]
  bento: Array<{ title: string; body: string }>
  comparePairs: Array<{ label: string; value: string }>
  assistantPlaceholder: string
  homeValueBody: string
  homeAboutTitle: string
  homeAboutBody: string
  homeAboutLink: string
  homeFinalTitle: string
  faqTitle: string
  pricingFaqIntro: string
  pricingDisclaimer: string
  pricingPlansTitle: string
  platformOverviewTitle: string
  pricingPlans: Array<{
    key: 'free' | 'plus' | 'pro'
    name: string
    description: string
    price: string
    cadence: string
    marker: string
    cta: string
    featured?: boolean
    features: string[]
  }>
}

export interface PageCopy {
  meta: PageMeta
  intro: string
  cta: string
  secondary?: string
  sections: Array<{ title: string; body: string; link?: string }>
  screenshots: ScreenshotProps[]
  faq?: Array<{ question: string; answer: string }>
}

const baseUi: Record<Locale, UiCopy> = {
  'pt-BR': {
    nav: { product: 'Produto', platform: 'Visão do sistema', tools: 'Ferramentas', compare: 'Comparar', pricing: 'Preços', resources: 'Recursos', login: 'Entrar', start: 'Começar grátis', explore: 'Explorar a plataforma', menu: 'Abrir menu', close: 'Fechar menu' },
    footer: { ctaTitle: 'A próxima brassagem começa com uma decisão melhor.', ctaBody: 'Receita, processo e memória no mesmo fio de contexto.', ctaAction: 'Explorar o produto', explore: 'Explorar', product: 'Produto', documentation: 'Documentação', modules: 'Módulos', exploreProcess: 'Entenda o ciclo completo do Brew Pilot', exploreModules: 'Receitas, estoque, lotes e produção', explorePricing: 'Free, Plus e Pro', exploreAbout: 'Conheça a ideia por trás do Brew Pilot', brewPilot: 'Brew Pilot', supportLegal: 'Suporte & Legal', eyebrow: 'Da receita ao copo', signature: 'Transforme cada brassagem em uma cerveja melhor.', resources: 'Recursos', recipes: 'Receitas e formulação', batches: 'Lotes e Brew Day', inventory: 'Estoque e custos', profiles: 'Perfis de produção', howItWorks: 'Como funciona', about: 'Sobre', support: 'Suporte', privacy: 'Privacidade', cookies: 'Cookies', terms: 'Termos', termsOfUse: 'Termos de uso' },
    common: { soon: 'Em breve', viewMore: 'Ver detalhes', appOnly: 'Disponível no aplicativo Brew Pilot', pending: 'Integração em preparação', backHome: 'Voltar para a home', email: 'E-mail de suporte', language: 'Idioma', privacyConsent: 'Consentimento de privacidade', productStories: 'Histórias do produto Brew Pilot', faq: 'FAQ' },
    consent: { title: 'Privacidade no seu ritmo', body: 'Usamos métricas somente com seu consentimento. Você pode mudar essa escolha a qualquer momento.', accept: 'Aceitar métricas', reject: 'Recusar', settings: 'Preferências de privacidade' },
    cycle: ['Criar receita', 'Planejar lote', 'Brassar', 'Acompanhar', 'Analisar', 'Evoluir'],
    cycleDescriptions: ['Crie a receita da cerveja que quer fazer.', 'Prepare tudo antes de ligar o fogo.', 'Execute com mais controle.', 'Registre o que realmente aconteceu.', 'Compare plano e resultado.', 'Use o lote para melhorar o próximo.'],
    bento: [{ title: 'Estoque', body: 'Saiba o que está disponível antes de planejar.' }, { title: 'Custos', body: 'Entenda o lote sem esconder o detalhe importante.' }, { title: 'Água', body: 'Guarde o perfil que influencia a próxima decisão.' }],
    comparePairs: [{ label: 'Brew Pilot', value: 'Contexto conectado' }, { label: 'Software tradicional', value: 'O ponto de partida' }],
    assistantPlaceholder: 'Placeholder de asset oficial',
    homeValueBody: 'Comece grátis e evolua conforme sua produção pede mais controle.',
    homeAboutTitle: 'O sistema acompanha a cerveja, não apenas a receita.',
    homeAboutBody: 'Receita, estoque, brassagem e histórico trabalham juntos. Você acompanha o que planejou, o que aconteceu e o que pode melhorar no próximo lote.',
    homeAboutLink: 'Como o Brew Pilot funciona',
    homeFinalTitle: 'Organize a próxima brassagem no Brew Pilot.',
    faqTitle: 'Respostas antes de começar.',
    pricingFaqIntro: 'O app mostra os detalhes da sua conta para manter valores, limites e contratação sempre atualizados.',
    pricingDisclaimer: 'Valores, limites e disponibilidade são definidos no Brew Pilot e podem variar por região, conta ou fase do produto.',
    pricingPlansTitle: 'Escolha o nível que acompanha seu próximo lote.',
    platformOverviewTitle: 'Tudo o que sustenta uma brassagem melhor.',
    pricingPlans: [
      { key: 'free', name: 'Free', description: 'Para começar a criar receitas e registrar suas primeiras brassagens.', price: 'R$ 0', cadence: 'para sempre', marker: 'Primeiro lote', cta: 'Começar grátis', features: ['Criação de receitas', 'Checklist de brassagem', 'Registro de lotes', 'Perfil de equipamento', 'Histórico essencial', 'Acesso à sua conta'] },
      { key: 'plus', name: 'Plus', description: 'Para quem produz com frequência e quer mais controle sobre receitas, estoque, perfis e histórico.', price: 'R$ 19,90', cadence: '/mês ou R$ 199/ano', marker: 'Para manter o ritmo', cta: 'Escolher Plus', featured: true, features: ['Tudo do Free, mais:', 'Receitas ilimitadas', 'Controle de estoque básico', 'Perfis de água e calculadoras', 'Histórico de lotes e versões', 'Sincronização com 1 dispositivo'] },
      { key: 'pro', name: 'Pro', description: 'Para quem quer recursos avançados, análises, histórico completo, exportações e o assistente Dr. Hoppin.', price: 'R$ 39,90', cadence: '/mês ou R$ 399/ano', marker: 'A experiência completa', cta: 'Escolher Pro', features: ['Tudo do Plus, mais:', 'Assistente de IA Dr. Hoppin', 'Exportação em PDF, BeerXML e JSON', 'Calculadoras avançadas', 'Histórico completo de lotes', 'Recursos avançados de análise', 'Acesso antecipado a novos recursos'] },
    ],
  },
  'en-US': {
    nav: { product: 'Product', platform: 'System overview', tools: 'Tools', compare: 'Compare', pricing: 'Pricing', resources: 'Resources', login: 'Log in', start: 'Start free', explore: 'Explore the platform', menu: 'Open menu', close: 'Close menu' },
    footer: { ctaTitle: 'The next brew starts with a better decision.', ctaBody: 'Recipe, process, and memory in one connected thread.', ctaAction: 'Explore the product', explore: 'Explore', product: 'Product', documentation: 'Documentation', modules: 'Modules', exploreProcess: 'Understand the complete Brew Pilot cycle', exploreModules: 'Recipes, inventory, batches and production', explorePricing: 'Free, Plus and Pro', exploreAbout: 'Learn about the idea behind Brew Pilot', brewPilot: 'Brew Pilot', supportLegal: 'Support & Legal', eyebrow: 'From recipe to glass', signature: 'Turn every brew into a better beer.', resources: 'Resources', recipes: 'Recipes and formulation', batches: 'Batches and Brew Day', inventory: 'Inventory and costs', profiles: 'Production profiles', howItWorks: 'How it works', about: 'About', support: 'Support', privacy: 'Privacy', cookies: 'Cookies', terms: 'Terms', termsOfUse: 'Terms of use' },
    common: { soon: 'Coming soon', viewMore: 'View details', appOnly: 'Available in the Brew Pilot app', pending: 'Integration in progress', backHome: 'Back to home', email: 'Support email', language: 'Language', privacyConsent: 'Privacy consent', productStories: 'Brew Pilot product stories', faq: 'FAQ' },
    consent: { title: 'Privacy at your pace', body: 'We use measurement only with your consent. You can change this choice at any time.', accept: 'Accept measurement', reject: 'Decline', settings: 'Privacy preferences' },
    cycle: ['Create recipe', 'Plan batch', 'Brew', 'Track', 'Analyze', 'Evolve'],
    cycleDescriptions: ['Shape the beer you want to make.', 'Prepare everything before turning on the heat.', 'Execute with less improvisation.', 'Record what actually happened.', 'Compare plan and result.', 'Improve the next batch.'],
    bento: [{ title: 'Inventory', body: 'Know what is available before you plan.' }, { title: 'Costs', body: 'Understand the batch without hiding the important detail.' }, { title: 'Water', body: 'Keep the profile that shapes the next decision.' }],
    comparePairs: [{ label: 'Brew Pilot', value: 'Connected context' }, { label: 'Traditional software', value: 'The starting point' }],
    assistantPlaceholder: 'Official asset placeholder',
    homeValueBody: 'Start free and grow as your production calls for more control.',
    homeAboutTitle: 'The system follows the beer, not just the recipe.',
    homeAboutBody: 'Recipes, inventory, brew day, and history work together. Follow what you planned, what happened, and what to improve in the next batch.',
    homeAboutLink: 'How Brew Pilot works',
    homeFinalTitle: 'Organize your next brew in Brew Pilot.',
    faqTitle: 'Answers before you start.',
    pricingFaqIntro: 'The app keeps your account details, limits, and billing options up to date.',
    pricingDisclaimer: 'Prices, limits, and availability are defined in the Brew Pilot app and may vary by account or region.',
    pricingPlansTitle: 'Choose the level that follows your next batch.',
    platformOverviewTitle: 'Everything that supports a better brew.',
    pricingPlans: [
      { key: 'free', name: 'Free', description: 'The essentials to create, test and organize your first recipes.', price: 'R$ 0', cadence: 'to get started', marker: 'First batch', cta: 'Open in the app', features: ['Recipe creation', 'Brew day checklist', 'Batch notes', 'Equipment profile', 'Essential history', 'Account access'] },
      { key: 'plus', name: 'Plus', description: 'More continuity for brewers who want to follow their brewery closely.', price: 'R$ 9', cadence: '/month', marker: 'Keep the rhythm', cta: 'View in the app', featured: true, features: ['Unlimited recipes', 'Basic inventory control', 'Sync with one device', 'Water profiles and calculators', 'Advanced editor views', 'Batch and version history'] },
      { key: 'pro', name: 'Pro', description: 'Advanced resources for an even more complete brewing operation.', price: 'R$ 19', cadence: '/month', marker: 'Complete experience', cta: 'Upgrade in the app', features: ['Plus recipes and inventory', 'Plus water profiles', 'Mr. Hoppin AI assistant', 'PDF, BeerXML and JSON exports', 'Advanced mash calculators', 'Complete batch history'] },
    ],
  },
  es: {
    nav: { product: 'Producto', platform: 'Visión del sistema', tools: 'Herramientas', compare: 'Comparar', pricing: 'Precios', resources: 'Recursos', login: 'Entrar', start: 'Empezar gratis', explore: 'Explorar la plataforma', menu: 'Abrir menú', close: 'Cerrar menú' },
    footer: { ctaTitle: 'La próxima elaboración empieza con una mejor decisión.', ctaBody: 'Receta, proceso y memoria en un mismo hilo de contexto.', ctaAction: 'Explorar el producto', explore: 'Explorar', product: 'Producto', documentation: 'Documentación', modules: 'Módulos', exploreProcess: 'Entiende el ciclo completo de Brew Pilot', exploreModules: 'Recetas, inventario, lotes y producción', explorePricing: 'Free, Plus y Pro', exploreAbout: 'Conoce la idea detrás de Brew Pilot', brewPilot: 'Brew Pilot', supportLegal: 'Soporte & Legal', eyebrow: 'De la receta al vaso', signature: 'Transforma cada elaboración en una cerveza mejor.', resources: 'Recursos', recipes: 'Recetas y formulación', batches: 'Lotes y Brew Day', inventory: 'Inventario y costes', profiles: 'Perfiles de producción', howItWorks: 'Cómo funciona', about: 'Sobre nosotros', support: 'Soporte', privacy: 'Privacidad', cookies: 'Cookies', terms: 'Términos', termsOfUse: 'Términos de uso' },
    common: { soon: 'Próximamente', viewMore: 'Ver detalles', appOnly: 'Disponible en la aplicación Brew Pilot', pending: 'Integración en preparación', backHome: 'Volver al inicio', email: 'Correo de soporte', language: 'Idioma', privacyConsent: 'Consentimiento de privacidad', productStories: 'Historias del producto Brew Pilot', faq: 'FAQ' },
    consent: { title: 'Privacidad a tu ritmo', body: 'Usamos métricas solo con tu consentimiento. Puedes cambiar esta elección cuando quieras.', accept: 'Aceptar métricas', reject: 'Rechazar', settings: 'Preferencias de privacidad' },
    cycle: ['Crear receta', 'Planificar lote', 'Elaborar', 'Acompañar', 'Analizar', 'Evolucionar'],
    cycleDescriptions: ['Da forma a la cerveza que quieres producir.', 'Prepara todo antes de encender el fuego.', 'Ejecuta con menos improvisación.', 'Registra lo que realmente ocurrió.', 'Compara el plan y el resultado.', 'Mejora el próximo lote.'],
    bento: [{ title: 'Inventario', body: 'Conoce lo disponible antes de planificar.' }, { title: 'Costes', body: 'Entiende el lote sin esconder el detalle importante.' }, { title: 'Agua', body: 'Guarda el perfil que influye en la próxima decisión.' }],
    comparePairs: [{ label: 'Brew Pilot', value: 'Contexto conectado' }, { label: 'Software tradicional', value: 'El punto de partida' }],
    assistantPlaceholder: 'Placeholder de asset oficial',
    homeValueBody: 'Empieza gratis y evoluciona cuando tu producción necesite más control.',
    homeAboutTitle: 'El sistema acompaña la cerveza, no solo la receta.',
    homeAboutBody: 'Receta, inventario, elaboración e historial trabajan juntos. Sigue lo que planeaste, lo que ocurrió y lo que puedes mejorar en el próximo lote.',
    homeAboutLink: 'Cómo funciona Brew Pilot',
    homeFinalTitle: 'Organiza tu próxima elaboración en Brew Pilot.',
    faqTitle: 'Respuestas antes de empezar.',
    pricingFaqIntro: 'La aplicación mantiene actualizados los detalles de tu cuenta, límites y contratación.',
    pricingDisclaimer: 'Los precios, límites y disponibilidad se definen en la aplicación Brew Pilot y pueden variar según la cuenta o región.',
    pricingPlansTitle: 'Elige el nivel que acompaña tu próximo lote.',
    platformOverviewTitle: 'Todo lo que sostiene una mejor elaboración.',
    pricingPlans: [
      { key: 'free', name: 'Free', description: 'Lo esencial para crear, probar y organizar tus primeras recetas.', price: 'R$ 0', cadence: 'para empezar', marker: 'Primer lote', cta: 'Abrir en la app', features: ['Creación de recetas', 'Checklist de elaboración', 'Registro de lotes', 'Perfil de equipo', 'Historial esencial', 'Acceso a tu cuenta'] },
      { key: 'plus', name: 'Plus', description: 'Más continuidad para quien quiere acompañar de cerca su cervecería.', price: 'R$ 9', cadence: '/mes', marker: 'Mantén el ritmo', cta: 'Ver en la app', featured: true, features: ['Recetas ilimitadas', 'Control de inventario básico', 'Sincronización con un dispositivo', 'Perfiles de agua y calculadoras', 'Vistas avanzadas del editor', 'Historial de lotes y versiones'] },
      { key: 'pro', name: 'Pro', description: 'Recursos avanzados para una operación cervecera aún más completa.', price: 'R$ 19', cadence: '/mes', marker: 'Experiencia completa', cta: 'Actualizar en la app', features: ['Recetas e inventario del Plus', 'Perfiles de agua del Plus', 'Asistente de IA Mr. Hoppin', 'Exportación a PDF, BeerXML y JSON', 'Calculadoras avanzadas de maceración', 'Historial completo de lotes'] },
    ],
  },
}

const screenshot = (id: string, label: string, alt: string, tone: ScreenshotProps['tone'] = 'wide'): ScreenshotProps => ({ id, label, alt, tone })

const content: Record<Locale, Record<MarketingPageKind, PageCopy>> = {
  'pt-BR': {
    home: {
      meta: { title: 'Brew Pilot | Sua melhor cerveja começa antes da brassagem', description: 'Conecte receitas, estoque e brassagens. Compare resultados e melhore sua próxima cerveja com o Brew Pilot.', heading: 'Transforme cada brassagem em uma cerveja melhor.', eyebrow: 'DA RECEITA AO COPO', path: '/' },
      intro: 'Planeje receitas, controle ingredientes, acompanhe cada etapa da brassagem e compare o planejado com o resultado. Tudo conectado em um único lugar.', cta: 'Começar grátis', secondary: 'Ver como funciona',
      sections: [
        { title: 'UM CICLO COMPLETO PARA CADA LOTE', body: 'Do plano ao próximo lote, tudo fica conectado.' },
        { title: 'O seu processo tem contexto', body: 'Equipamento, mostura, fermentação e água deixam de ser notas soltas e passam a formar um método.' },
        { title: 'Cada passo aparece na hora certa', body: 'Leve a receita para a brassagem com timers, adições e alterações no mesmo fluxo, sem voltar para anotações espalhadas.' },
        { title: 'Aprender começa no histórico', body: 'Compare versões, custos e resultados para repetir o que funcionou e ajustar o próximo lote.' },
        { title: 'Tudo que a receita precisa para avançar', body: 'Estoque, custos e água ficam conectados ao processo, sem transformar a home em um painel.' },
        { title: 'Inteligência no momento certo', body: 'Dr. Hoppin ajuda a organizar perguntas e próximos passos. Recursos de IA entram quando estiverem prontos.' },
        { title: 'Uma plataforma feita para evoluir com você', body: 'Mais intenção antes da brassagem. Mais aprendizado depois dela.' },
      ],
      screenshots: [screenshot('hero-recipe-builder', 'Placeholder de screenshot: construtor de receita', 'Espaço reservado para o screenshot do construtor de receita'), screenshot('brew-day-checklist', 'Placeholder de screenshot: checklist de brassagem', 'Espaço reservado para o screenshot do checklist de brassagem', 'tall'), screenshot('batch-history', 'Placeholder de screenshot: histórico de lotes', 'Espaço reservado para o screenshot do histórico de lotes'), screenshot('inventory', 'Placeholder de screenshot: estoque conectado', 'Espaço reservado para o screenshot do estoque'), screenshot('costs', 'Placeholder de screenshot: custos por lote', 'Espaço reservado para o screenshot de custos'), screenshot('water', 'Placeholder de screenshot: perfil de água', 'Espaço reservado para o screenshot do perfil de água'), screenshot('recipe-versioning', 'Placeholder de screenshot: histórico e versões', 'Espaço reservado para o screenshot de histórico e versões')],
      faq: [{ question: 'O Brew Pilot serve para quem está começando?', answer: 'Sim. A plataforma organiza decisões e registros sem exigir que você domine todos os cálculos desde o primeiro lote.' }, { question: 'Preciso importar minhas receitas?', answer: 'Não. Você pode começar uma receita nova e construir seu histórico dentro do Brew Pilot.' }, { question: 'O que muda entre Free, Plus e Pro?', answer: 'Os planos ampliam o espaço e a continuidade do processo. O app mostra os limites e recursos disponíveis para a sua conta.' }, { question: 'Onde acontece a contratação?', answer: 'Cadastro, login, cobrança e troca de plano acontecem no aplicativo. O site apresenta a proposta e leva você para lá.' }],
    },
    features: { meta: { title: 'Produto | Brew Pilot', description: 'Conheça o fluxo do Brew Pilot, da ideia da receita ao aprendizado do lote.', heading: 'O produto acompanha o raciocínio por trás da receita.', eyebrow: 'Produto', path: '/features' }, intro: 'Uma plataforma conectada para transformar intenção em prática e prática em aprendizado.', cta: 'Começar grátis', secondary: 'Voltar para a home', sections: [{ title: 'Planeje antes de abrir a panela', body: 'Receitas, perfis e decisões importantes começam com uma estrutura que você consegue revisar.' }, { title: 'Brasse com um plano claro', body: 'O Brew Day leva o que foi planejado para o momento em que cada escolha importa.' }, { title: 'Registre o que aconteceu', body: 'Lote e histórico criam uma memória prática, pronta para a próxima versão.' }, { title: 'Evolua com evidência', body: 'Compare o resultado com o que você pretendia fazer e ajuste com mais confiança.' }], screenshots: [screenshot('recipe-builder', 'Placeholder de screenshot: planejamento da receita', 'Espaço reservado para o screenshot do planejamento da receita'), screenshot('equipment-profile', 'Placeholder de screenshot: perfil de equipamento', 'Espaço reservado para o screenshot do perfil de equipamento'), screenshot('brew-day-checklist', 'Placeholder de screenshot: execução do Brew Day', 'Espaço reservado para o screenshot do Brew Day', 'tall'), screenshot('recipe-versioning', 'Placeholder de screenshot: versionamento', 'Espaço reservado para o screenshot de versionamento')], faq: [] },
    platform: { meta: { title: 'Visão do sistema | Brew Pilot', description: 'Conheça o sistema Brew Pilot e veja como receitas, lotes, estoque e perfis trabalham juntos.', heading: 'Um sistema para acompanhar a cerveja inteira.', eyebrow: 'Visão do sistema', path: '/platform' }, intro: 'O Brew Pilot organiza as partes que fazem uma brassagem avançar, sem separar planejamento, execução e aprendizado.', cta: 'Explorar o produto', secondary: 'Ver planos', sections: [{ title: 'Receitas que guardam o raciocínio', body: 'Crie, revise e evolua receitas mantendo escolhas, ingredientes e resultados no mesmo contexto.' }, { title: 'Brew Day orientado por contexto', body: 'Leve o plano para a execução e registre mudanças enquanto elas ainda estão acontecendo.' }, { title: 'Lotes que viram memória', body: 'Acompanhe fermentação, resultados e versões para saber o que repetir na próxima brassagem.' }, { title: 'Estoque e custos no mesmo fluxo', body: 'Saiba o que está disponível e entenda o impacto do lote antes de decidir.' }, { title: 'Perfis para repetir o que funciona', body: 'Equipamento, mostura, fermentação, água e carbonatação deixam de ser notas soltas.' }, { title: 'Conta e planos sem surpresa', body: 'A conta do app concentra acesso, assinatura e configurações em um único lugar.' }], screenshots: [screenshot('platform-recipes', 'Placeholder de screenshot: receitas e editor', 'Espaço reservado para o screenshot de receitas e editor'), screenshot('platform-brew-day', 'Placeholder de screenshot: Brew Day', 'Espaço reservado para o screenshot do Brew Day'), screenshot('platform-batches', 'Placeholder de screenshot: lotes e histórico', 'Espaço reservado para o screenshot de lotes e histórico'), screenshot('platform-inventory', 'Placeholder de screenshot: estoque e ingredientes', 'Espaço reservado para o screenshot de estoque e ingredientes'), screenshot('platform-profiles', 'Placeholder de screenshot: perfis cervejeiros', 'Espaço reservado para o screenshot de perfis cervejeiros'), screenshot('platform-account', 'Placeholder de screenshot: conta e planos', 'Espaço reservado para o screenshot de conta e planos')], faq: [] },
    pricing: { meta: { title: 'Preços | Brew Pilot', description: 'Entenda o valor do Brew Pilot e acesse os planos no aplicativo.', heading: 'O valor aparece quando o processo fica mais claro.', eyebrow: 'Planos no aplicativo', path: '/pricing' }, intro: 'O marketing explica a proposta. Planos, preços e contratação vivem no app Brew Pilot.', cta: 'Ver planos no Brew Pilot', secondary: 'Conhecer o produto', sections: [{ title: 'Mais clareza antes do lote', body: 'Planeje melhor antes da brassagem e entre no lote sabendo o que importa.' }, { title: 'Mais memória depois do lote', body: 'Histórico e versionamento tornam cada brassagem uma fonte para a próxima.' }, { title: 'Detalhes de assinatura no app', body: 'A área de planos do aplicativo mostra as opções disponíveis para sua conta.' }], screenshots: [], faq: [{ question: 'Qual plano faz sentido para começar?', answer: 'O Free cobre o primeiro fluxo de receita e registro. Quando você precisar de mais continuidade, Plus e Pro ampliam o processo dentro do app.' }, { question: 'Posso trocar de plano depois?', answer: 'Sim, a área de conta do Brew Pilot é o lugar certo para consultar as opções disponíveis e iniciar uma mudança.' }, { question: 'Onde acontece a contratação?', answer: 'Cadastro, login, cobrança e contratação acontecem no aplicativo Brew Pilot. O site apenas apresenta a proposta e leva você para lá.' }, { question: 'O que muda no plano Pro?', answer: 'O Pro reúne os recursos do Plus e acrescenta o assistente Mr. Hoppin, exportações e calculadoras avançadas do app.' }] },
    compare: { meta: { title: 'Comparar | Brew Pilot', description: 'Entenda a proposta do Brew Pilot para conectar planejamento, brassagem e aprendizado.', heading: 'Compare propostas. Escolha o processo que faz sentido para você.', eyebrow: 'Comparar', path: '/compare' }, intro: 'O Brew Pilot não precisa diminuir outras ferramentas para explicar o próprio foco.', cta: 'Explorar a plataforma', secondary: 'Ver ferramentas', sections: [{ title: 'Menos troca de contexto', body: 'Receita, equipamento, lote e histórico vivem em uma mesma linha de trabalho.' }, { title: 'Mais contexto para aprender', body: 'O objetivo não é acumular telas. É deixar a decisão seguinte mais informada.' }, { title: 'Comparações específicas em preparação', body: 'Páginas individuais só serão publicadas quando houver fontes oficiais e verificáveis para cada alegação.' }], screenshots: [] },
    tools: { meta: { title: 'Ferramentas | Brew Pilot', description: 'Veja as ferramentas cervejeiras planejadas para o Brew Pilot.', heading: 'Ferramentas úteis, no momento certo.', eyebrow: 'Ferramentas', path: '/tools' }, intro: 'Estamos preparando ferramentas que ajudam a responder perguntas práticas sem separar cálculo de contexto.', cta: 'Explorar a plataforma', secondary: 'Voltar para o produto', sections: [{ title: 'Calculadora de ABV', body: 'Estime o álcool da receita com os dados que já fazem parte do seu processo.' }, { title: 'Calculadora de IBU', body: 'Organize a contribuição de amargor sem perder de vista a receita inteira.' }, { title: 'Calculadora de priming', body: 'Planeje a carbonatação como parte do lote, não como uma etapa isolada.' }], screenshots: [] },
    about: { meta: { title: 'Sobre o Brew Pilot', description: 'Conheça a visão do Brew Pilot para organizar receitas, brassagens e histórico em um só sistema.', heading: 'Um sistema técnico para quem leva a brassagem a sério.', eyebrow: 'Sobre o Brew Pilot', path: '/about' }, intro: 'O Brew Pilot nasceu para conectar o raciocínio da receita ao trabalho que acontece na bancada, sem esconder a parte manual do processo.', cta: 'Explorar a plataforma', secondary: 'Falar com suporte', sections: [{ title: 'Domínio cervejeiro em contexto', body: 'Receitas, equipamento, mostura, fermentação, água, estoque e lotes são partes do mesmo processo, não notas soltas.' }, { title: 'Dados que ajudam a decidir', body: 'Cada registro existe para responder uma pergunta prática: o que foi planejado, o que mudou e o que vale repetir.' }, { title: 'O site explica. O app executa.', body: 'O marketing apresenta a lógica e os limites do produto. A execução, a conta, os planos e os dados ficam no aplicativo Brew Pilot.' }], screenshots: [] },
    contact: { meta: { title: 'Contato | Brew Pilot', description: 'Encontre o canal de suporte do Brew Pilot e acompanhe a integração de contato.', heading: 'Vamos manter o canal aberto.', eyebrow: 'Contato e suporte', path: '/contact' }, intro: 'O canal de suporte fica configurado por ambiente. O formulário conectado à API Brew Pilot está em preparação.', cta: 'Explorar a plataforma', secondary: 'Voltar para a home', sections: [{ title: 'Suporte por e-mail', body: 'Quando disponível, o endereço configurado aparece nesta página para orientar sua mensagem.' }, { title: 'Integração em preparação', body: 'Não simulamos envio. A API pública de contato definirá endpoint, segurança e respostas antes da ativação.' }], screenshots: [] },
    comparison: { meta: { title: 'Comparativo em preparação | Brew Pilot', description: 'Esta página comparativa está em preparação e ainda não está disponível para indexação.', heading: 'Comparativo em preparação.', eyebrow: 'Rascunho', path: '/compare' }, intro: 'A página só será publicada quando cada afirmação tiver fonte oficial e revisão de conteúdo.', cta: 'Voltar para comparar', secondary: 'Explorar a plataforma', sections: [{ title: 'Conteúdo responsável', body: 'Não inventamos limites, recursos ou diferenças de outras ferramentas.' }], screenshots: [] },
    'not-found': { meta: { title: 'Página não encontrada | Brew Pilot', description: 'A página que você procurou não existe.', heading: 'Esta página ainda não existe.', eyebrow: '404', path: '/' }, intro: 'Volte para a home e continue explorando o Brew Pilot.', cta: 'Voltar para a home', sections: [], screenshots: [] },
  },
  'en-US': {} as Record<PageKind, PageCopy>,
  es: {} as Record<PageKind, PageCopy>,
}

const localizedOverrides: Record<Locale, Partial<Record<PageKind, PageCopy>>> = {
  'pt-BR': {},
  'en-US': {
    home: { ...content['pt-BR'].home, meta: { ...content['pt-BR'].home.meta, title: 'Brew Pilot | Your best beer starts before brew day', description: 'Connect recipes, inventory, and brew days. Compare results and improve your next beer with Brew Pilot.', heading: 'Your best beer starts before brew day.', eyebrow: 'FROM RECIPE TO GLASS', path: '/' }, intro: 'Plan recipes, manage ingredients, track every brew-day step, and compare the plan with the result. All connected in one place.', cta: 'Start free', secondary: 'See the system', sections: content['pt-BR'].home.sections.map((s, i) => ({ ...s, title: ['One line of thinking for every batch', 'Your process has context', 'Every step appears when it matters', 'Learning starts in history', 'Everything a recipe needs to move forward', 'Intelligence at the right moment', 'A platform that evolves with you'][i], body: ['From idea to learning, Brew Pilot keeps decisions and results in one place.', 'Equipment, mash, fermentation, and water become a method instead of scattered notes.', 'Take the recipe into brew day with timers, additions, and changes in one flow.', 'Compare versions, costs, and outcomes to repeat what worked and adjust the next batch.', 'Inventory, costs, and water stay connected to the process without turning the home into a dashboard.', 'Dr. Hoppin helps organize questions and next steps. AI features arrive when they are ready.', 'More intention before brew day. More learning after it.'][i] })), screenshots: content['pt-BR'].home.screenshots.map((s) => ({ ...s, label: s.label.replace('Placeholder de screenshot:', 'Screenshot placeholder:'), alt: s.alt.replace('Espaço reservado para o screenshot', 'Reserved space for the screenshot') })), faq: [{ question: 'Is Brew Pilot useful if I am just starting?', answer: 'Yes. The platform organizes decisions and records without requiring you to master every calculation on your first batch.' }, { question: 'Do I need to import recipes?', answer: 'No. Start a new recipe and build your history inside Brew Pilot.' }, { question: 'What changes between Free, Plus, and Pro?', answer: 'Plans expand the space and continuity of your process. The app shows the limits and resources available to your account.' }, { question: 'Where does billing happen?', answer: 'Signup, login, billing, and plan changes happen in the app. The site explains the offer and takes you there.' }] },
    features: { ...content['pt-BR'].features, meta: { ...content['pt-BR'].features.meta, title: 'Product | Brew Pilot', description: 'Explore the Brew Pilot flow, from recipe idea to batch learning.', heading: 'The product follows the thinking behind the recipe.', eyebrow: 'Product' }, intro: 'A connected platform for turning intent into practice, and practice into learning.', cta: 'Start free', secondary: 'Back to home' },
    platform: { ...content['pt-BR'].platform, meta: { ...content['pt-BR'].platform.meta, title: 'System overview | Brew Pilot', description: 'See how recipes, batches, inventory, and brewing profiles work together in Brew Pilot.', heading: 'One system for the whole brew.', eyebrow: 'System overview' }, intro: 'Brew Pilot organizes the parts that move a brew forward, connecting planning, execution, and learning.', cta: 'Explore the product', secondary: 'View plans', sections: content['pt-BR'].platform.sections.map((s, i) => ({ ...s, title: ['Recipes that keep the reasoning', 'Brew Day with context', 'Batches become memory', 'Inventory and costs in one flow', 'Profiles for repeatable brewing', 'Account and plans without surprises'][i], body: ['Create, revise, and evolve recipes while keeping choices, ingredients, and outcomes in context.', 'Take the plan into execution and record changes while they are happening.', 'Follow fermentation, results, and versions to know what to repeat next time.', 'See what is available and understand the batch impact before deciding.', 'Equipment, mash, fermentation, water, and carbonation stop being scattered notes.', 'The app account keeps access, subscription, and settings in one place.'][i] })), screenshots: content['pt-BR'].platform.screenshots.map((s) => ({ ...s, label: `Screenshot placeholder: ${s.id.replaceAll('-', ' ')}`, alt: `Reserved space for the ${s.id.replaceAll('-', ' ')} screenshot` })) },
    pricing: { ...content['pt-BR'].pricing, meta: { ...content['pt-BR'].pricing.meta, title: 'Pricing | Brew Pilot', description: 'Understand Brew Pilot value and access plans in the app.', heading: 'Value appears when the process gets clearer.', eyebrow: 'Plans in the app' }, intro: 'Marketing explains the proposition. Plans, prices, and billing live in the Brew Pilot app.', cta: 'View plans in Brew Pilot', secondary: 'Explore the product', faq: [{ question: 'Which plan makes sense to start?', answer: 'Free covers the first recipe and batch record flow. When you need more continuity, Plus and Pro expand the process in the app.' }, { question: 'Can I change plans later?', answer: 'Yes. The Brew Pilot account area is where you can review the available options and start a change.' }, { question: 'Where does checkout happen?', answer: 'Signup, login, billing, and checkout happen in the Brew Pilot app. The site explains the offer and takes you there.' }, { question: 'What changes with Pro?', answer: 'Pro includes Plus capabilities and adds Mr. Hoppin, exports, and advanced calculators from the app.' }] },
    compare: { ...content['pt-BR'].compare, meta: { ...content['pt-BR'].compare.meta, title: 'Compare | Brew Pilot', description: 'Understand Brew Pilot approach to connecting planning, brewing, and learning.', heading: 'Compare approaches. Choose the process that fits you.', eyebrow: 'Compare' }, intro: 'Brew Pilot does not need to diminish other tools to explain its focus.', cta: 'Explore the platform', secondary: 'See tools' },
    tools: { ...content['pt-BR'].tools, meta: { ...content['pt-BR'].tools.meta, title: 'Tools | Brew Pilot', description: 'See the brewing tools planned for Brew Pilot.', heading: 'Useful tools, at the right moment.', eyebrow: 'Tools' }, intro: 'We are preparing tools that answer practical questions without separating calculation from context.', cta: 'Explore the platform', secondary: 'Back to product' },
    about: { ...content['pt-BR'].about, meta: { ...content['pt-BR'].about.meta, title: 'About Brew Pilot', description: 'See how Brew Pilot connects recipes, brew days, and history in one system.', heading: 'A technical system for brewers who care about the process.', eyebrow: 'About Brew Pilot' }, intro: 'Brew Pilot connects the reasoning behind a recipe to the work that happens at the bench, without hiding the hands-on part of brewing.', cta: 'Explore the platform', secondary: 'Contact support', sections: content['pt-BR'].about.sections.map((s, i) => ({ ...s, title: ['Brewing domain in context', 'Data that helps you decide', 'The site explains. The app executes.'][i], body: ['Recipes, equipment, mash, fermentation, water, inventory, and batches are parts of one process, not scattered notes.', 'Every record exists to answer a practical question: what was planned, what changed, and what is worth repeating.', 'The marketing site explains the product and its boundaries. Execution, account, plans, and data live in the Brew Pilot app.'][i] })) },
    contact: { ...content['pt-BR'].contact, meta: { ...content['pt-BR'].contact.meta, title: 'Contact | Brew Pilot', description: 'Find Brew Pilot support and follow the contact integration.', heading: 'Let us keep the channel open.', eyebrow: 'Contact and support' }, intro: 'Support is configured by environment. The form connected to the Brew Pilot API is in preparation.', cta: 'Explore the platform', secondary: 'Back to home' },
    comparison: { ...content['pt-BR'].comparison, meta: { ...content['pt-BR'].comparison.meta, title: 'Comparison in preparation | Brew Pilot', description: 'This comparison page is in preparation and is not available for indexing.', heading: 'Comparison in preparation.', eyebrow: 'Draft' }, intro: 'This page will be published when every claim has an official source and content review.', cta: 'Back to compare', secondary: 'Explore the platform' },
  },
  es: {
    home: { ...content['pt-BR'].home, meta: { ...content['pt-BR'].home.meta, title: 'Brew Pilot | Tu mejor cerveza empieza antes de elaborar', description: 'Conecta recetas, inventario y elaboraciones. Compara resultados y mejora tu próxima cerveza con Brew Pilot.', heading: 'Tu mejor cerveza empieza antes de elaborar.', eyebrow: 'DE LA RECETA AL VASO', path: '/' }, intro: 'Planifica recetas, controla ingredientes, sigue cada etapa de la elaboración y compara lo planificado con el resultado. Todo conectado en un solo lugar.', cta: 'Empezar gratis', secondary: 'Conocer el sistema', sections: content['pt-BR'].home.sections.map((s, i) => ({ ...s, title: ['Una línea de pensamiento para cada lote', 'Tu proceso tiene contexto', 'Cada paso aparece cuando importa', 'Aprender empieza en el historial', 'Todo lo que una receta necesita para avanzar', 'Inteligencia en el momento adecuado', 'Una plataforma que evoluciona contigo'][i], body: ['De la idea al aprendizaje, Brew Pilot mantiene decisiones y resultados en un mismo lugar.', 'Equipo, macerado, fermentación y agua dejan de ser notas sueltas y forman un método.', 'Lleva la receta al día de elaboración con temporizadores, adiciones y cambios en un mismo flujo.', 'Compara versiones, costes y resultados para repetir lo que funcionó y ajustar el próximo lote.', 'Inventario, costes y agua se conectan al proceso sin convertir la home en un panel.', 'Dr. Hoppin ayuda a ordenar preguntas y próximos pasos. Las funciones de IA llegarán cuando estén listas.', 'Más intención antes de elaborar. Más aprendizaje después.'][i] })), screenshots: content['pt-BR'].home.screenshots.map((s) => ({ ...s, label: s.label.replace('Placeholder de screenshot:', 'Placeholder de captura:'), alt: s.alt.replace('Espaço reservado para o screenshot', 'Espacio reservado para la captura') })), faq: [{ question: '¿Brew Pilot sirve para quienes empiezan?', answer: 'Sí. La plataforma organiza decisiones y registros sin exigir que domines todos los cálculos desde el primer lote.' }, { question: '¿Tengo que importar mis recetas?', answer: 'No. Puedes comenzar una receta nueva y construir tu historial dentro de Brew Pilot.' }, { question: '¿Qué cambia entre Free, Plus y Pro?', answer: 'Los planes amplían el espacio y la continuidad del proceso. La aplicación muestra los límites y recursos disponibles para tu cuenta.' }, { question: '¿Dónde se realiza la contratación?', answer: 'El registro, inicio de sesión, cobro y cambio de plan ocurren en la aplicación. El sitio presenta la propuesta y te lleva allí.' }] },
    features: { ...content['pt-BR'].features, meta: { ...content['pt-BR'].features.meta, title: 'Producto | Brew Pilot', description: 'Conoce el flujo de Brew Pilot, desde la idea de la receta hasta el aprendizaje del lote.', heading: 'El producto acompaña el razonamiento detrás de la receta.', eyebrow: 'Producto' }, intro: 'Una plataforma conectada para convertir intención en práctica y práctica en aprendizaje.', cta: 'Empezar gratis', secondary: 'Volver al inicio' },
    platform: { ...content['pt-BR'].platform, meta: { ...content['pt-BR'].platform.meta, title: 'Visión del sistema | Brew Pilot', description: 'Conoce cómo recetas, lotes, inventario y perfiles cerveceros trabajan juntos en Brew Pilot.', heading: 'Un sistema para toda la elaboración.', eyebrow: 'Visión del sistema' }, intro: 'Brew Pilot organiza las partes que hacen avanzar una elaboración y conecta planificación, ejecución y aprendizaje.', cta: 'Explorar el producto', secondary: 'Ver planes', sections: content['pt-BR'].platform.sections.map((s, i) => ({ ...s, title: ['Recetas que guardan el razonamiento', 'Brew Day con contexto', 'Los lotes se vuelven memoria', 'Inventario y costes en un mismo flujo', 'Perfiles para repetir lo que funciona', 'Cuenta y planes sin sorpresas'][i], body: ['Crea, revisa y evoluciona recetas manteniendo decisiones, ingredientes y resultados en contexto.', 'Lleva el plan a la ejecución y registra los cambios mientras ocurren.', 'Sigue la fermentación, los resultados y las versiones para saber qué repetir.', 'Conoce lo disponible y entiende el impacto del lote antes de decidir.', 'Equipo, macerado, fermentación, agua y carbonatación dejan de ser notas sueltas.', 'La cuenta de la aplicación concentra acceso, suscripción y configuración.'][i] })), screenshots: content['pt-BR'].platform.screenshots.map((s) => ({ ...s, label: `Placeholder de captura: ${s.id.replaceAll('-', ' ')}`, alt: `Espacio reservado para la captura de ${s.id.replaceAll('-', ' ')}` })) },
    pricing: { ...content['pt-BR'].pricing, meta: { ...content['pt-BR'].pricing.meta, title: 'Precios | Brew Pilot', description: 'Entiende el valor de Brew Pilot y accede a los planes en la aplicación.', heading: 'El valor aparece cuando el proceso se vuelve más claro.', eyebrow: 'Planes en la aplicación' }, intro: 'El marketing explica la propuesta. Los planes, precios y contratación viven en la aplicación Brew Pilot.', cta: 'Ver planes en Brew Pilot', secondary: 'Conocer el producto', faq: [{ question: '¿Qué plan tiene sentido para empezar?', answer: 'Free cubre el primer flujo de recetas y registro de lotes. Cuando necesites más continuidad, Plus y Pro amplían el proceso en la aplicación.' }, { question: '¿Puedo cambiar de plan después?', answer: 'Sí. El área de cuenta de Brew Pilot permite consultar las opciones disponibles e iniciar el cambio.' }, { question: '¿Dónde se contrata?', answer: 'El registro, inicio de sesión, cobro y contratación ocurren en la aplicación Brew Pilot. El sitio presenta la propuesta y te lleva allí.' }, { question: '¿Qué cambia en Pro?', answer: 'Pro reúne las capacidades de Plus y añade Mr. Hoppin, exportaciones y calculadoras avanzadas de la aplicación.' }] },
    compare: { ...content['pt-BR'].compare, meta: { ...content['pt-BR'].compare.meta, title: 'Comparar | Brew Pilot', description: 'Entiende la propuesta de Brew Pilot para conectar planificación, elaboración y aprendizaje.', heading: 'Compara propuestas. Elige el proceso que tiene sentido para ti.', eyebrow: 'Comparar' }, intro: 'Brew Pilot no necesita disminuir otras herramientas para explicar su foco.', cta: 'Explorar la plataforma', secondary: 'Ver herramientas' },
    tools: { ...content['pt-BR'].tools, meta: { ...content['pt-BR'].tools.meta, title: 'Herramientas | Brew Pilot', description: 'Conoce las herramientas cerveceras planeadas para Brew Pilot.', heading: 'Herramientas útiles, en el momento adecuado.', eyebrow: 'Herramientas' }, intro: 'Preparamos herramientas que ayudan a responder preguntas prácticas sin separar el cálculo del contexto.', cta: 'Explorar la plataforma', secondary: 'Volver al producto' },
    about: { ...content['pt-BR'].about, meta: { ...content['pt-BR'].about.meta, title: 'Sobre Brew Pilot', description: 'Conoce cómo Brew Pilot conecta recetas, elaboraciones e historial en un solo sistema.', heading: 'Un sistema técnico para quienes se toman en serio el proceso.', eyebrow: 'Sobre Brew Pilot' }, intro: 'Brew Pilot conecta el razonamiento de la receta con el trabajo en la bancada, sin ocultar la parte manual de la elaboración.', cta: 'Explorar la plataforma', secondary: 'Contactar soporte', sections: content['pt-BR'].about.sections.map((s, i) => ({ ...s, title: ['Dominio cervecero en contexto', 'Datos para decidir mejor', 'El sitio explica. La aplicación ejecuta.'][i], body: ['Recetas, equipo, macerado, fermentación, agua, inventario y lotes forman un mismo proceso, no notas sueltas.', 'Cada registro responde una pregunta práctica: qué se planeó, qué cambió y qué vale la pena repetir.', 'El marketing presenta el producto y sus límites. La ejecución, la cuenta, los planes y los datos viven en la aplicación Brew Pilot.'][i] })) },
    contact: { ...content['pt-BR'].contact, meta: { ...content['pt-BR'].contact.meta, title: 'Contacto | Brew Pilot', description: 'Encuentra el canal de soporte de Brew Pilot y sigue la integración de contacto.', heading: 'Mantengamos abierto el canal.', eyebrow: 'Contacto y soporte' }, intro: 'El soporte se configura por entorno. El formulario conectado a la API de Brew Pilot está en preparación.', cta: 'Explorar la plataforma', secondary: 'Volver al inicio' },
    comparison: { ...content['pt-BR'].comparison, meta: { ...content['pt-BR'].comparison.meta, title: 'Comparativa en preparación | Brew Pilot', description: 'Esta página comparativa está en preparación y no está disponible para indexación.', heading: 'Comparativa en preparación.', eyebrow: 'Borrador' }, intro: 'La página se publicará cuando cada afirmación tenga una fuente oficial y revisión de contenido.', cta: 'Volver a comparar', secondary: 'Explorar la plataforma' },
  },
}

for (const locale of ['en-US', 'es'] as Locale[]) {
  content[locale] = {} as Record<MarketingPageKind, PageCopy>
  for (const kind of Object.keys(content['pt-BR']) as MarketingPageKind[]) {
    content[locale][kind] = localizedOverrides[locale][kind] || content['pt-BR'][kind]
  }
}

content['en-US'].home.meta.heading = 'Turn every brew into a better beer.'
content.es.home.meta.heading = 'Convierte cada elaboración en una cerveza mejor.'
content['en-US'].home.secondary = 'See how it works'
content.es.home.secondary = 'Ver cómo funciona'
content['en-US'].home.sections[0].title = 'A COMPLETE CYCLE FOR EVERY BATCH'
content.es.home.sections[0].title = 'UN CICLO COMPLETO PARA CADA LOTE'
content['en-US'].home.sections[0].body = 'From the plan to the next batch, everything stays connected.'
content.es.home.sections[0].body = 'Del plan al próximo lote, todo queda conectado.'
baseUi['en-US'].cycleDescriptions = ['Create the recipe for the beer you want to make.', 'Prepare everything before turning on the heat.', 'Execute with more control.', 'Record what actually happened.', 'Compare plan and result.', 'Use the batch to improve the next one.']
baseUi.es.cycleDescriptions = ['Crea la receta de la cerveza que quieres hacer.', 'Prepara todo antes de encender el fuego.', 'Ejecuta con más control.', 'Registra lo que realmente ocurrió.', 'Compara el plan y el resultado.', 'Usa el lote para mejorar el siguiente.']

const localizedSections: Record<'en-US' | 'es', Partial<Record<MarketingPageKind, Array<[string, string]>>>> = {
  'en-US': {
    features: [['Plan before the kettle', 'Recipes, profiles, and important decisions start with a structure you can review.'], ['Brew with a clear plan', 'Brew Day takes what you planned into the moment when each choice matters.'], ['Record what happened', 'Batch and history create a practical memory for the next version.'], ['Evolve with evidence', 'Compare the result with what you intended and adjust with more confidence.']],
    pricing: [['More clarity before the batch', 'Plan better before brew day and enter the batch knowing what matters.'], ['More memory after the batch', 'History and versioning make every brew a source for the next one.'], ['Subscription details in the app', 'The app plan area shows the options available for your account.']],
    compare: [['Less context switching', 'Recipe, equipment, batch, and history live in one line of work.'], ['More context to learn', 'The goal is not more screens. It is a better-informed next decision.'], ['Specific comparisons in preparation', 'Individual pages will go live only when official, verifiable sources exist for every claim.']],
    tools: [['ABV calculator', 'Estimate recipe alcohol with the data already part of your process.'], ['IBU calculator', 'Organize bitterness contribution without losing sight of the full recipe.'], ['Priming calculator', 'Plan carbonation as part of the batch, not as an isolated step.']],
    about: [['Beer is practice and memory', 'A good tool respects the bench, the time, and the decisions of the person making it.'], ['Clarity before complexity', 'We start with the line of thinking that helps make the next brew better.'], ['Built in cycles', 'The product grows through real questions, honest records, and room to learn.']],
    contact: [['Support by email', 'When available, the configured address appears here to guide your message.'], ['Integration in preparation', 'We do not simulate sending. The public contact API will define endpoint, security, and responses first.']],
  },
  es: {
    features: [['Planifica antes de abrir la olla', 'Las recetas, perfiles y decisiones importantes empiezan con una estructura que puedes revisar.'], ['Elabora con un plan claro', 'Brew Day lleva lo planificado al momento en que cada decisión importa.'], ['Registra lo que ocurrió', 'El lote y el historial crean una memoria práctica para la próxima versión.'], ['Evoluciona con evidencia', 'Compara el resultado con lo que querías hacer y ajusta con más confianza.']],
    pricing: [['Más claridad antes del lote', 'Planifica mejor antes de elaborar y llega al lote sabiendo qué importa.'], ['Más memoria después del lote', 'El historial y las versiones convierten cada elaboración en una fuente para la siguiente.'], ['Detalles de suscripción en la app', 'El área de planes de la aplicación muestra las opciones de tu cuenta.']],
    compare: [['Menos cambios de contexto', 'La receta, el equipo, el lote y el historial viven en una misma línea de trabajo.'], ['Más contexto para aprender', 'El objetivo no es acumular pantallas. Es informar mejor la próxima decisión.'], ['Comparativas en preparación', 'Las páginas individuales se publicarán cuando existan fuentes oficiales y verificables para cada afirmación.']],
    tools: [['Calculadora de ABV', 'Estima el alcohol de la receta con los datos que ya forman parte de tu proceso.'], ['Calculadora de IBU', 'Organiza el amargor sin perder de vista la receta completa.'], ['Calculadora de priming', 'Planifica la carbonatación como parte del lote, no como un paso aislado.']],
    about: [['La cerveza es práctica y memoria', 'Una buena herramienta respeta la mesa de trabajo, el tiempo y las decisiones de quien elabora.'], ['Claridad antes que complejidad', 'Empezamos por la línea de razonamiento que ayuda a mejorar la próxima elaboración.'], ['Construido en ciclos', 'El producto crece con preguntas reales, registros honestos y espacio para aprender.']],
    contact: [['Soporte por correo', 'Cuando esté disponible, la dirección configurada aparecerá aquí para orientar tu mensaje.'], ['Integración en preparación', 'No simulamos envíos. La API pública de contacto definirá primero el endpoint, la seguridad y las respuestas.']],
  },
}

const translatedMedia = (locale: 'en-US' | 'es', media: ScreenshotProps[]): ScreenshotProps[] => media.map((item) => ({
  ...item,
  label: locale === 'en-US' ? `Screenshot placeholder: ${item.id.replaceAll('-', ' ')}` : `Placeholder de captura: ${item.id.replaceAll('-', ' ')}`,
  alt: locale === 'en-US' ? `Reserved space for the ${item.id.replaceAll('-', ' ')} screenshot` : `Espacio reservado para la captura de ${item.id.replaceAll('-', ' ')}`,
}))

for (const locale of ['en-US', 'es'] as const) {
  for (const kind of Object.keys(content[locale]) as MarketingPageKind[]) {
    const copy = content[locale][kind]
    const pairs = localizedSections[locale][kind]
    if (copy && pairs) copy.sections = pairs.map(([title, body]) => ({ title, body }))
    if (copy) copy.screenshots = translatedMedia(locale, copy.screenshots)
  }
}

export const getUi = (locale: Locale): UiCopy => baseUi[locale]
export const getPageCopy = (locale: Locale, kind: MarketingPageKind): PageCopy => content[locale][kind] || content['pt-BR']['not-found']
export const supportedLocales: Locale[] = ['pt-BR', 'en-US', 'es']
